site_name: Olympus Docs
theme: material
pages:
- Home: 'index.md'
- Developer: 
    - Modules: 
        - 'Get Started': 'developer/modules/get-started.md'
        - 'Client Modules': 'developer/modules/client-modules/get-started.md'
        - 'Service Modules': 'developer/modules/service-modules/get-started.md'
    - Tools: 'developer/tools/get-started.md'